FROM delhomme/upscb-ngs-preprocessing:shellinabox
MAINTAINER Nicolas Delhomme (nicolas.delhomme@umu.se)

#########
### Working dir
#########
RUN	mkdir build
WORKDIR /build

#########
### Aptitude packages
#########
RUN apt update && apt install -y cmake automake curl libboost-all-dev

#########
### STAR
#########
RUN wget https://github.com/alexdobin/STAR/archive/2.7.0e.tar.gz && \
	tar -xf 2.7.0e.tar.gz
WORKDIR STAR-2.7.0e/bin/Linux_x86_64_static
RUN cp STAR /usr/local/bin
WORKDIR /build

#########
### kallisto
#########
RUN wget https://github.com/pachterlab/kallisto/releases/download/v0.45.1/kallisto_linux-v0.45.1.tar.gz && \
	tar -xf kallisto_linux-v0.45.1.tar.gz
WORKDIR kallisto_linux-v0.45.1
RUN cp kallisto /usr/local/bin
WORKDIR /build

#########
### Salmon
#########
WORKDIR /build
# TODO update salmon
#RUN git clone https://github.com/COMBINE-lab/salmon.git && \
#	cd salmon && git checkout v0.13.1 && mkdir build && cd build && \
#    cmake .. && make -j 4 && make install && cp ../lib/lib* /usr/local/lib/. && \
#    cp ../bin/salmon /usr/local/bin/.
#RUN wget https://github.com/COMBINE-lab/salmon/releases/download/v1.1.0/salmon-1.1.0_linux_x86_64.tar.gz && 
# mkdir build && cd build && wget https://github.com/COMBINE-lab/salmon/releases/download/v1.1.0/salmon-1.1.0_linux_x86_64.tar.gz && tar -zxf salmon-1.1.0_linux_x86_64.tar.gz && cp salmon-latest_linux_x86_64/bin/salmon /usr/local/bin/ && cp salmon-latest_linux_x86_64/lib/lib* /usr/local/lib/

#########
### Pip installs: HTSeq
#########
# PySam
#RUN pip install htseq

#########
### gffread
#########
WORKDIR /build
RUN git clone https://github.com/gpertea/gclib && \
    git clone https://github.com/gpertea/gffread && \
    cd gffread && make && cp gffread /usr/local/bin

#########
### Clean up
#########
WORKDIR /
RUN rm -rf /build

#########
### Ports and CMD
#########
CMD ["/usr/bin/supervisord","-c","/etc/supervisor/conf.d/supervisord.conf"]
