FROM delhomme/upscb-jbrowse
MAINTAINER Nicolas Delhomme (nicolas.delhomme@umu.se)

#########
### Aptitude packages
#########
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y cmake default-jre git ftp libbz2-dev \
	libcairo2-dev libcurl4-openssl-dev libpango1.0-dev liblzma-dev librocksdb-dev nano openssl \
	openssh-server python3-dev python3-pip rapidjson-dev \
	shellinabox tree wget zlib1g-dev

#########
### Working dir
#########
RUN	mkdir build
WORKDIR /build

#########
### Java tools: Trimmomatic, FastQC
#########
RUN wget http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip && \
	unzip fastqc_v0.11.9.zip && \
	chmod +x FastQC/fastqc && \
	cp -r FastQC /usr/share/ && \
	ln -s /usr/share/FastQC/fastqc /usr/bin/ && \
	wget http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/Trimmomatic-0.39.zip && \
	unzip Trimmomatic-0.39.zip && \
	cp -r Trimmomatic-0.39 /usr/share/ && \
	echo '#!/bin/bash\njava -jar /usr/share/Trimmomatic-0.39/trimmomatic-0.39.jar $@' > /usr/bin/trimmomatic && \
	chmod +x /usr/bin/trimmomatic

#########
### SortmeRNA 4.2
#########
# Building from source is annoying so we fetch the release binaries
RUN wget https://github.com/biocore/sortmerna/releases/download/v4.2.0/sortmerna-4.2.0-Linux.sh && \
	mkdir /opt/sortmerna && sh sortmerna-4.2.0-Linux.sh --skip-license --prefix=/opt/sortmerna

RUN echo "export PATH=/opt/sortmerna/bin:${PATH}" >> /home/training/.profile

#RUN wget https://github.com/biocore/sortmerna/releases/download/v3.0.3/sortmerna-3.0.3-Linux_U18.tar.gz && \
#     tar -zxf sortmerna-3.0.3-Linux_U18.tar.gz && cp sortmerna-3.0.3-Linux/bin/* /usr/local/bin
# However we also clone the repos to get the rRNA-dbs and other scripts
#RUN git clone https://github.com/biocore/sortmerna.git
#WORKDIR sortmerna
#RUN cp scripts/merge-paired-reads.sh /usr/local/bin && cp scripts/unmerge-paired-reads.sh /usr/local/bin && \
#	cp -r rRNA_databases/ /usr/share/
#WORKDIR /usr/share/rRNA_databases
#ADD scripts/phiX.fasta /usr/share/rRNA_databases/phiX.fasta
#COPY scripts/indexdb.sh /usr/share/rRNA_databases/
#COPY scripts/makeDbList.sh /usr/share/rRNA_databases/
#RUN ./indexdb.sh
#ENV SORTMERNA_DB=$(makeDbList.sh)
#"/usr/share/rRNA_databases/rfam-5s-database-id98.fasta,/usr/share/rRNA_databases/index/rfam-5s-database-id98:/usr/share/rRNA_databases/silva-euk-28s-id98.fasta,/usr/share/rRNA_databases/index/silva-euk-28s-id98:/usr/share/rRNA_databases/silva-euk-18s-id95.fasta,/usr/share/rRNA_databases/index/silva-euk-18s-id95:/usr/share/rRNA_databases/silva-arc-16s-id95.fasta,/usr/share/rRNA_databases/index/silva-arc-16s-id95:/usr/share/rRNA_databases/silva-bac-16s-id90.fasta,/usr/share/rRNA_databases/index/silva-bac-16s-id90:/usr/share/rRNA_databases/silva-arc-23s-id98.fasta,/usr/share/rRNA_databases/index/silva-arc-23s-id98:/usr/share/rRNA_databases/silva-bac-23s-id98.fasta,/usr/share/rRNA_databases/index/silva-bac-23s-id98:/usr/share/rRNA_databases/rfam-5.8s-database-id98.fasta,/usr/share/rRNA_databases/index/rfam-5.8s-database-id98:/usr/share/rRNA_databases/phiX.fasta,/usr/share/rRNA_databases/index/phiX"
#RUN echo "export SORTMERNA_DB=$(/usr/share/rRNA_databases/makeDbList.sh)" >> /home/training/.profile
WORKDIR /build

#########
### Pip installs: multiQC
#########
RUN git clone https://github.com/ewels/MultiQC && cd MultiQC && \
    pip3 install numpy matplotlib && \
    python3 setup.py install

#########
### genometools
#########
RUN wget http://genometools.org/pub/genometools-1.5.10.tar.gz && \
    tar -xf genometools-1.5.10.tar.gz && cd genometools-1.5.10 && \
    make errorcheck=no && make install

#########
### HTSlib tools: Samtools, Bcftools
#########
WORKDIR /build
RUN wget https://github.com/samtools/samtools/releases/download/1.11/samtools-1.11.tar.bz2 \
	https://github.com/samtools/bcftools/releases/download/1.11/bcftools-1.11.tar.bz2 \
	https://github.com/samtools/htslib/releases/download/1.11/htslib-1.11.tar.bz2 && \
	tar -xf htslib-1.11.tar.bz2
WORKDIR htslib-1.11
RUN ./configure && make && make install
WORKDIR /build
RUN tar -xf bcftools-1.11.tar.bz2
WORKDIR bcftools-1.11
RUN make && make install
WORKDIR /build
RUN tar -xf samtools-1.11.tar.bz2
WORKDIR samtools-1.11
RUN make && make install
WORKDIR /build

#########
### bedtools
#########
WORKDIR /build
RUN wget https://github.com/arq5x/bedtools2/releases/download/v2.29.2/bedtools-2.29.2.tar.gz && \
    tar -xf bedtools-2.29.2.tar.gz && cd bedtools2 && \
    ln -s /usr/bin/python3 /usr/bin/python && make -j 4 && make install

#########
### Clean up
#########
WORKDIR /
RUN rm -rf /build

#########
# Apache access to the home dir
#########
RUN ln -sf /home/training /var/www/html/home

#########
# Squash python3 error
#########
RUN echo "export LC_ALL=C.UTF-8" >> /home/training/.profile
RUN echo "export LANG=C.UTF-8" >> /home/training/.profile

#########
### Supervisor
#########
ADD supervisord-shellinabox.conf /etc/supervisor/conf.d/supervisord.conf

#########
### Volumes
#########
RUN mkdir /home/training/share
VOLUME /home/training/share

#########
### Ports and CMD
#########
EXPOSE 22 4200
CMD ["/usr/bin/supervisord","-c","/etc/supervisor/conf.d/supervisord.conf"]
