FROM delhomme/upscb-jbrowse2
MAINTAINER Nicolas Delhomme (nicolas.delhomme@umu.se)

# versions
ARG CPU=4

# bedtools, fastqc, htslib (bcftools), sortmerma, trimmomatic
ARG BDT_VERSION=2.30.0
ARG FQC_VERSION=0.11.9
ARG HTL_VERSION=1.17
ARG SMR_VERSION=4.3.6
ARG TMM_VERSION=0.39

# Aptitude packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y cmake default-jre git ftp \
	libcurl4-openssl-dev nano openssl python3-dev python3-pip tree

# Working dir
RUN	mkdir build
WORKDIR /build

# Java tools: Trimmomatic, FastQC
RUN curl -L -O http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v${FQC_VERSION}.zip && \
	unzip fastqc_v${FQC_VERSION}.zip && \
	chmod +x FastQC/fastqc && \
	cp -r FastQC /usr/share/ && \
	ln -s /usr/share/FastQC/fastqc /usr/bin

RUN curl -L -O http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/Trimmomatic-${TMM_VERSION}.zip && \
	unzip Trimmomatic-${TMM_VERSION}.zip && \
	cp -r Trimmomatic-${TMM_VERSION} /usr/share/ && \
	echo '#!/bin/bash\njava -jar /usr/share/Trimmomatic-'${TMM_VERSION}'/trimmomatic-'${TMM_VERSION}'.jar $@' > /usr/bin/trimmomatic && \
	chmod +x /usr/bin/trimmomatic

# SortmeRNA
# Building from source is annoying so we fetch the release binaries
RUN curl -L -O  https://github.com/biocore/sortmerna/releases/download/v${SMR_VERSION}/sortmerna-${SMR_VERSION}-Linux.sh && \
	mkdir /opt/sortmerna && sh sortmerna-${SMR_VERSION}-Linux.sh --skip-license --prefix=/opt/sortmerna

RUN echo 'export PATH=/opt/sortmerna/bin:${PATH}' >> /home/training/.profile

# Pip installs: multiQC
RUN git clone https://github.com/ewels/MultiQC && cd MultiQC && \
    pip3 install numpy matplotlib && \
    python3 setup.py install

# HTSlib tools: Bcftools
RUN curl -L -O  https://github.com/samtools/bcftools/releases/download/${HTL_VERSION}/bcftools-${HTL_VERSION}.tar.bz2 && \
	tar -xf bcftools-${HTL_VERSION}.tar.bz2 && cd bcftools-${HTL_VERSION} && make -j ${CPU} && make install

# bedtools
RUN curl -L -O  https://github.com/arq5x/bedtools2/releases/download/v${BDT_VERSION}/bedtools-${BDT_VERSION}.tar.gz && \
    tar -xf bedtools-${BDT_VERSION}.tar.gz && cd bedtools2 && \
    ln -s /usr/bin/python3 /usr/bin/python && make -j ${CPU} && make install

# Clean up
WORKDIR /
RUN rm -rf /build

# Squash python3 error
RUN echo "export LC_ALL=C.UTF-8" >> /home/training/.profile
RUN echo "export LANG=C.UTF-8" >> /home/training/.profile

# Volumes
RUN mkdir /home/training/share
VOLUME /home/training/share

# Command
CMD ["/usr/bin/supervisord","-c","/etc/supervisor/conf.d/supervisord.conf"]
